pipeline:
  name: mouadlambda
  identifier: mouadlambda
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: lambda
        identifier: lambda
        description: ""
        type: IACM
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          workspace: infraLambda
          execution:
            steps:
              - step:
                  type: IACMTerraformPlugin
                  name: init
                  identifier: init
                  spec:
                    command: init
                  timeout: 1h
              - step:
                  type: IACMTerraformPlugin
                  name: plan
                  identifier: plan
                  spec:
                    command: plan
                  timeout: 10m
              - step:
                  type: IACMTerraformPlugin
                  name: apply
                  identifier: apply
                  spec:
                    command: apply
                  timeout: 1h
        tags: {}
  properties:
    ci:
      codebase:
        connectorRef: AMJIDMOUAD
        repoName: InfraHome
        build: <+input>
        sparseCheckout: []
