pipeline:
  name: mouadlambda
  identifier: mouadlambda
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: lambda
        identifier: lambda
        description: ""
        type: IACM
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          workspace: infraLambda
          execution:
            steps:
              - step:
                  type: Run
                  name: provision
                  identifier: provision
                  spec:
                    shell: Sh
                    command: |-
                      terraform init

                      terraform apply -destroy -auto-approve

                      terraform apply -auto-approve
                    envVariables:
                      AWS_ACCESS_KEY_ID: <+secrets.getValue("AWS_ACCESS_KEY_ID")>
                      AWS_SECRET_ACCESS_KEY: <+secrets.getValue("AWS_SECRET_ACCESS_KEY")>
        tags: {}
  properties:
    ci:
      codebase:
        connectorRef: AMJIDMOUAD
        repoName: InfraHome
        build: <+input>
        sparseCheckout: []
